export class Details {
  days: any[] = [
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Satarday',
    'Sunday',
  ];
  students: any[] = [
    {
      users: [
        {
          userID: '215705552',
          name: 'Maenetja Mankgasha',
          Bio: 'Business Applications',
          image: '../../../assets/img 2.jpg',
        },
        {
          userID: '202096462',
          name: 'Mashia Nare Bruce',
          Bio: 'System Analyst',
          image: '../../../assets/img 4.jpg',
        },
        {
          userID: '202034689',
          name: 'Kenneth Chuenyana',
          Bio: 'Software Developer',
          image: '../../../assets/img.jpg',
        },
        {
          userID: '202001237',
          name: 'Mashabela Pheladi',
          Bio: 'Applications Developer',
          image: '../../../assets/img 3.jpg',
        },
      ],
      subjects: [
        {
          subjID: 'SDV2013',
          userID: '215705552',
          subjName: 'Information Systems',
          yearReg: '2020',
          lecture: 'Mr Lefota',
          institution: 'Tshwane University of Technology',
          mark: '85',
        },
        {
          subjID: 'SAN7553',
          userID: '202096462',
          subjName: 'Computing Fundermentals',
          yearReg: '2020',
          lecture: 'Mr Makaba',
          institution: 'Tshwane University of Technology',
          mark: '20',
        },
        {
          subjID: 'CMS4290',
          userID: '202034689',
          subjName: 'Computing System',
          yearReg: '2020',
          lecture: 'Mrs Maserumule',
          institution: 'Tshwane University of Technology',
          mark: '45',
        },
        {
          subjID: 'SSW8723',
          userID: '202001237',
          subjName: 'System Sofware',
          yearReg: '2020',
          lecture: 'Mr Seloka',
          institution: 'Tshwane University of Technology',
          mark: '55',
        },
        //
        /*{
          subjID: 'IFM5832',
          userID: '215705552',
          subjName: 'Informatics',
          yearReg: '2020',
          lecture: 'Mrs Tshweni',
          institution: 'Tshwane University of Technology',
          mark: '75',
        },
        {
          subjID: 'CFM5111',
          userID: '202096462',
          subjName: 'Computing Fundermental II',
          yearReg: '2020',
          lecture: 'Mr Kampole',
          institution: 'Tshwane University of Technology',
          mark: '70',
        },
        {
          subjID: 'ITM4290',
          userID: '202034689',
          subjName: 'IT Mathematics',
          yearReg: '2020',
          lecture: 'Mr Chuene',
          institution: 'Tshwane University of Technology',
          mark: '60',
        },
        {
          subjID: 'SSWB8723',
          userID: '202001237',
          subjName: 'System Software IIB',
          yearReg: '2020',
          lecture: 'Mrs Tshweni',
          institution: 'Tshwane University of Technology',
          mark: '55',
        },*/
      ],
      //second subject
      subjects2: [
        {
          subjID: 'IFM5832',
          userID: '215705552',
          subjName: 'Informatics',
          yearReg: '2020',
          lecture: 'Mrs Tshweni',
          institution: 'Tshwane University of Technology',
          mark: '76',
        },
        {
          subjID: 'CFM5111',
          userID: '202096462',
          subjName: 'Computing Fundermental II',
          yearReg: '2020',
          lecture: 'Mr Kampole',
          institution: 'Tshwane University of Technology',
          mark: '70',
        },
        {
          subjID: 'ITM4290',
          userID: '202034689',
          subjName: 'IT Mathematics',
          yearReg: '2020',
          lecture: 'Mr Chuene',
          institution: 'Tshwane University of Technology',
          mark: '60',
        },
        {
          subjID: 'SSWB8723',
          userID: '202001237',
          subjName: 'System Software IIB',
          yearReg: '2020',
          lecture: 'Mrs Tshweni',
          institution: 'Tshwane University of Technology',
          mark: '60',
        },
        //
      ],
    },
  ];
}
